-- CheqUp round-two exercise: starting schema
--
-- A starting point you own and may change. It is intentionally minimal:
-- adapt, extend, or replace it as your design requires.
--
-- Written for PostgreSQL. If you chose SQLite, adapt the types
-- (JSONB to TEXT, TIMESTAMPTZ to TEXT/DATETIME, the identity column to
-- INTEGER PRIMARY KEY).

CREATE TABLE members (
    id          INTEGER PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE submissions (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   INTEGER NOT NULL REFERENCES members(id),
    answers     JSONB NOT NULL,   -- the member's raw answers
    outcome     TEXT,             -- the computed result
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Two seeded members, matching the ids used by the X-Member-Id auth.
INSERT INTO members (id) VALUES (1), (2);
